### ISSUE TITLE
Add a network pytest mark for tests that use the network

### ISSUE THREAD

**Issue by mcepl** [alejandrogallo/python-doi#1]
* python-doi version: 0.2
* Python version: various
* Operating System: openSUSE/Tumbleweed

### Description

Sometimes it's useful to have the tests that use the network marked so they can be skipped easily when we know the network is not available.

This is useful for example on SUSE and openSUSE's build servers. When building our packages the network is disabled so we can assure reproducible builds (among other benefits). With this mark, it's easier to skip tests that can not succeed.

Proposed patch:

```patch
---
 setup.cfg         |    4 +++-
 tests/test_doi.py |    4 ++++
 2 files changed, 7 insertions(+), 1 deletion(-)

--- a/setup.cfg
+++ b/setup.cfg
@@ -5,7 +5,9 @@ universal = 1
 exclude = docs
 
 [tool:pytest]
-collect_ignore = ['setup.py']
+markers =
+    net: marks tests that call use the net (using the URL endpoint, deselect with '-k "not net"')
+
 
 [mypy]
 disallow_redefinition = True
--- a/tests/test_doi.py
+++ b/tests/test_doi.py
@@ -3,6 +3,8 @@
 import os
 from pkg_resources import parse_version
 
+import pytest
+
 from doi import (
     validate_doi, find_doi_in_text, __version__, pdf_to_doi,
     get_real_url_from_doi
@@ -14,6 +16,7 @@ def test_valid_version() -> None:
     assert parse_version(__version__) >= parse_version("0.1.0")
 
 
+@pytest.mark.net
 def test_validate_doi() -> None:
     data = [
         ('10.1063/1.5081715',
@@ -38,6 +41,7 @@ def test_validate_doi() -> None:
             assert str(e) == 'HTTP 404: DOI not found'
 
 
+@pytest.mark.net
 def test_get_real_url_from_doi() -> None:
     data = [
         ('10.1016/S0009-2614(97)04014-1',
```

**Comment by alejandrogallo** [comment]
thank you, this is useful, we should do this too in papis, can you do a pr?

**Comment by mcepl** [comment]
I am sorry, but I am a packager for couple of thousand Python packages for SUSE/openSUSE so I really cannot make git clones for all of them. Putting patches to tickets is probably most I can do. Hopefully it is not a big problem for you. Of course, the patch has been released to the public domain, do whatever you want to do with it.

**Comment by alejandrogallo** [comment]
fair enough, I made a commit in your name, if you don't consent to it
I will ammend the commit, thank you again
https://github.com/papis/python-doi/commit/051856058f3917b33f039e803902188f16e511df
